const bookGenres = [
  "Fiction",
  "Literary Fiction",
  "Historical Fiction",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Horror",
  "Non-Fiction",
  "Biography/Autobiography",
  "Memoir",
  "Essay",
  "Journalism",
  "True Crime",
  "Self-Help",
  "Philosophy",
  "Poetry",
  "Epic Poetry",
  "Sonnet",
  "Haiku",
  "Free Verse",
  "Narrative Poetry",
  "Drama",
  "Tragedy",
  "Comedy",
  "Historical Drama",
  "Children's Literature",
  "Picture Books",
  "Middle-Grade Fiction",
  "Young Adult (YA) Fiction",
  "Romance",
  "Historical Romance",
  "Contemporary Romance",
  "Paranormal Romance",
  "Science",
  "Popular Science",
  "Scientific Theory",
  "Science History",
  "Fantasy",
  "High Fantasy",
  "Urban Fantasy",
  "Mystery/Thriller",
  "Crime Fiction",
  "Detective Fiction",
  "Psychological Thriller",
  "Historical",
  "Historical Fiction",
  "Historical Non-Fiction",
  "Adventure",
  "Action-Adventure",
  "Survival Fiction",
  "Humor/Satire",
  "Comedy",
  "Satirical Fiction",
  "Mystery",
  "Cozy Mystery",
  "Hardboiled Mystery",
  "Biography",
  "Autobiography",
  "Memoir",
  "Horror",
  "Supernatural Horror",
  "Psychological Horror",
  "Religious/Spiritual",
  "Religious Fiction",
  "Spiritual Non-Fiction",
  "Graphic Novels/Comics",
  "Superhero Comics",
  "Graphic Memoirs",
  "Self-Help/Motivational",
  "Personal Development",
  "Inspirational",
  "Cookbooks",
  "Culinary Non-Fiction",
  "Recipe Collections",
  "Travel",
  "Travelogue",
  "Adventure Travel",
  "Science Fiction",
  "Hard Science Fiction",
  "Space Opera",
  "Social Science",
  "Sociology",
  "Psychology",
  "Reference",
  "Encyclopedias",
  "Dictionaries",
  "Educational",
  "Textbooks",
  "Academic Publications",
  "Business/Economics",
  "Business Strategy",
  "Economic Theory",
];

export default bookGenres;
